name: Accuracy comparison (low coverage)
datasets:
  validation:
    separator: "\t"
    path: ?input.validation
    offer-excel: true
views:
  validation:
    dataset: validation
    desc: |
      ### Accuracy comparison for low coverage samples
      Accuracy comparison is performed with Orthanq, Optitype, HLA-LA and arcasHLA, for four HLA loci.
      Call rate is calculated by dividing the number of samples that the HLA typer gives a prediction by the total number of samples.
      Accuracy is calculated by dividing the number of correctly predicted HLA genotypes by the total number of samples.
    page-size: 25
    render-table:
      columns:
        regex('.+Accuracy'):
          plot:
            ticks:
              scale: linear
              domain:
                - 0
                - 100
        "arcasHLA_Call_Rate":
          precision: 2