name: Evaluation table
datasets:
  A_tp_fp:
    path: ?input.A_tp_fp
    offer-excel: true
    separator: "\t"
  B_tp_fp:
    path: ?input.B_tp_fp
    offer-excel: true
    separator: "\t"
  C_tp_fp:
    path: ?input.C_tp_fp
    offer-excel: true
    separator: "\t"
  DQB1_tp_fp:
    path: ?input.DQB1_tp_fp
    offer-excel: true
    separator: "\t"
default-view: A_tp_fp
views:     
  A_tp_fp:
    dataset: A_tp_fp
    desc: |
      ## Evaluation table for locus A
      This table contains ground truth and the predictions made by all tools: orthanq, optitype, arcasHLA and HLA-LA.
      The following shows the different classes of evaluation, in respective columns in the table.
        1. TP (blue)
        2. FP (red)
        3. no call by the tool (white)
        4. call, but the allele that was called is not considered in the truth set according to the criteria in the truth paper (i.e., not in the database at that time, VAF too low).
    render-table:
      columns:
        arcasHLA:
          display-mode: hidden
        arcasHLA evaluation:
          label: arcasHLA
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["arcasHLA"] } 
        optitype:
          display-mode: hidden
        optitype evaluation:
          label: optitype
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["optitype"] } 
        HLA-LA:
          display-mode: hidden
        HLA-LA evaluation:
          label: HLA-LA
          ellipsis: 27
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["HLA-LA"] } 
        orthanq:
          display-mode: hidden
        orthanq evaluation:
          label: orthanq
          ellipsis: 21
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["orthanq"] } 
  B_tp_fp:
    dataset: B_tp_fp
    desc: |
      ## Evaluation table for locus B
      This table contains ground truth and the predictions made by all tools: orthanq, optitype, arcasHLA and HLA-LA.
      The following shows the different classes of evaluation, in respective columns in the table.
        1. TP (blue)
        2. FP (red)
        3. no call by the tool (white)
        4. call, but the allele that was called is not considered in the truth set according to the criteria in the truth paper (i.e., not in the database at that time, VAF too low).
    render-table:
      columns:
        arcasHLA:
          display-mode: hidden
        arcasHLA evaluation:
          label: arcasHLA
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["arcasHLA"] } 
        optitype:
          display-mode: hidden
        optitype evaluation:
          label: optitype
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["optitype"] } 
        HLA-LA:
          display-mode: hidden
        HLA-LA evaluation: 
          label: HLA-LA
          ellipsis: 27
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["HLA-LA"] } 
        orthanq:
          display-mode: hidden
        orthanq evaluation:
          label: orthanq
          ellipsis: 21
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["orthanq"] } 
  C_tp_fp:
    dataset: C_tp_fp
    desc: |
      ## Evaluation table for locus C
      This table contains ground truth and the predictions made by all tools: orthanq, optitype, arcasHLA and HLA-LA.
      The following shows the different classes of evaluation, in respective columns in the table.
        1. TP (blue)
        2. FP (red)
        3. no call by the tool (white)
        4. call, but the allele that was called is not considered in the truth set according to the criteria in the truth paper (i.e., not in the database at that time, VAF too low).
    render-table:
      columns:
        arcasHLA:
          display-mode: hidden
        arcasHLA evaluation:
          label: arcasHLA
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["arcasHLA"] } 
        optitype:
          display-mode: hidden
        optitype evaluation:
          label: optitype
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["optitype"] } 
        HLA-LA:
          display-mode: hidden
        HLA-LA evaluation:
          label: HLA-LA
          ellipsis: 27
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["HLA-LA"] } 
        orthanq:
          display-mode: hidden
        orthanq evaluation:
          label: orthanq
          ellipsis: 21
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["orthanq"] } 
  DQB1_tp_fp:
    dataset: DQB1_tp_fp
    desc: |
      ## Evaluation table for locus DQB1
      This table contains ground truth and the predictions made by all tools: orthanq, optitype, arcasHLA and HLA-LA.
      The following shows the different classes of evaluation, in respective columns in the table.
        1. TP (blue)
        2. FP (red)
        3. no call by the tool (white)
        4. call, but the allele that was called is not considered in the truth set according to the criteria in the truth paper (i.e., not in the database at that time, VAF too low).
    render-table:
      columns:
        arcasHLA:
          display-mode: hidden
        arcasHLA evaluation:
          label: arcasHLA
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["arcasHLA"] } 
        HLA-LA:
          display-mode: hidden
        HLA-LA evaluation:
          label: HLA-LA
          ellipsis: 33
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["HLA-LA"] } 
        orthanq:
          display-mode: hidden
        orthanq evaluation:
          label: orthanq
          ellipsis: 27
          plot:
            heatmap:
              scale: ordinal
              domain:
                - TP
                - FP
                - no call
                - allele not considered in the truth set
              range:
                - "#4A7BB7"
                - "#DD3D2D"
                - "#FFFFFF"
                - "#F67E4B"
              custom-content: |
                function(value, row) { return row["orthanq"] } 