__use_yte__: true
name: All predictions density table
datasets:
  density table:
    separator: "\t"
    path: ?input.tp_fp_table
    offer-excel: true
views:
  density table:
    dataset: density table
    desc: |
      ### Density table
      Density table for all predictions made by Orthanq.
    page-size: 25
    render-table:
      columns:
        Best_Density:
          plot:
            ticks:
              scale: linear
              domain:
                - 0
                - 1