name: Evaluation results
datasets:
  validation:
    separator: "\t"
    path: ?input.validation
    offer-excel: true
  orthanq-report:
    separator: "\t"
    path: ?input.orthanq
    offer-excel: true  
  arcashla-report:
    separator: "\t"
    path: ?input.arcasHLA
    offer-excel: true
  hla_la-report:
    separator: "\t"
    path: ?input.hla_la
    offer-excel: true
  optitype-report:
    separator: "\t"
    path: ?input.optitype
    offer-excel: true
  samples_evaluated:
    separator: "\t"
    path: ?input.samples_evaluated
    offer-excel: true
  individuals_no_fastq:
    separator: "\t"
    path: ?input.individuals_no_fastq
    offer-excel: true
  samples_low_coverage:
    separator: "\t"
    path: ?input.samples_low_coverage
    offer-excel: true
  preprocessing:
    path: ?input.preprocessing_table
    offer-excel: true
  genotyping:
    path: ?input.genotyping_table
    offer-excel: true
views:
  validation:
    dataset: validation
    desc: |
      ### Validation
      This table contains validation results
    page-size: 25
    render-table:
      columns:
        regex('.+Accuracy'):
          plot:
            ticks:
              scale: linear
              domain:
                - 0
                - 100
        "arcasHLA - Call Rate":
          precision: 2
  orthanq-report:
    dataset: orthanq-report
    desc: |
      ## Orthanq
      This table contains orthanq predictions
  arcashla-report:
    dataset: arcashla-report
    desc: |
      ## arcasHLA
      This table contains arcasHLA predictions
  hla_la-report:
    dataset: hla_la-report
    desc: |
      ## HLA-LA
      This table contains HLA-LA predictions
  optitype-report:
    dataset: optitype-report
    desc: |
      ## Optitype
      This table contains Optitype predictions
  samples_evaluated:
    dataset: samples_evaluated
    desc: |
      ## Ground truth of evaluated samples
      This table contains ground_truth values for all evaluated samples (1000 Genomes CEU population) in the paper.
  individuals_no_fastq:
    dataset: individuals_no_fastq
    desc: |
      ## Samples with no available fastq data
      This table contains samples with no available fastq data.
  samples_low_coverage:
    dataset: samples_low_coverage
    desc: |
      ## Samples with low coverage
      This table contains samples with low coverage fastq data, hence they were excluded from the evaluation.
  preprocessing:
    dataset: preprocessing
    desc: |
      ## Runtimes of all tools including all the preprocessing steps.
  genotyping:
    dataset: genotyping
    desc: |
      ## Runtimes of all tools including only the "HLA typing" or "calling" commmands.
