name: Evaluation results
datasets:
  validation:
    separator: "\t"
    path: ?input.validation
    offer-excel: true
  orthanq-report:
    separator: "\t"
    path: ?input.orthanq
    offer-excel: true  
  arcashla-report:
    separator: "\t"
    path: ?input.arcasHLA
    offer-excel: true
  hla_la-report:
    separator: "\t"
    path: ?input.hla_la
    offer-excel: true
  optitype-report:
    separator: "\t"
    path: ?input.optitype
    offer-excel: true
  sample_sheet:
    path: ?input.sample_sheet
    offer-excel: true
    links:
      link to orthanq:
        column: Run_Accession
        table-row: orthanq-report/sample
        optional: True
      link to arcasHLA:
        column: Run_Accession
        table-row: arcashla-report/sample
        optional: True
      link to HLA-LA:
        column: Run_Accession
        table-row: hla_la-report/sample
        optional: True
      link to optitype:
        column: Run_Accession
        table-row: optitype-report/sample
        optional: True
  runtimes:
    path: ?input.runtimes_table
    offer-excel: true
default-view: sample_sheet
views:
  validation:
    dataset: validation
    desc: |
      ### Validation
      This table contains validation results
    page-size: 25
    render-table:
      columns:
        regex('.+Accuracy'):
          plot:
            ticks:
              scale: linear
              domain:
                - 0
                - 100
        "arcasHLA_Call_Rate":
          precision: 2
  orthanq-report:
    dataset: orthanq-report
    desc: |
      ## Orthanq
      This table contains orthanq predictions
    render-table:
      columns:
        sample:
          link-to-url:
            SRA:
              url: "https://www.ncbi.nlm.nih.gov/sra/{value}"
        A:
          ellipsis: 21
        B:
          ellipsis: 21
        C:
          ellipsis: 21
        DQA1:
          ellipsis: 27
        DQB1:
          ellipsis: 27
  arcashla-report:
    dataset: arcashla-report
    desc: |
      ## arcasHLA
      This table contains arcasHLA predictions
    render-table:
      columns:
        sample:
          link-to-url:
            SRA:
              url: "https://www.ncbi.nlm.nih.gov/sra/{value}"
  hla_la-report:
    dataset: hla_la-report
    desc: |
      ## HLA-LA
      This table contains HLA-LA predictions
    render-table:
      columns:
        sample:
          link-to-url:
            SRA:
              url: "https://www.ncbi.nlm.nih.gov/sra/{value}"
        A:
          ellipsis: 27
        B:
          ellipsis: 27
        C:
          ellipsis: 27
        DQA1:
          ellipsis: 33
        DQB1:
          ellipsis: 33          
  optitype-report:
    dataset: optitype-report
    desc: |
      ## Optitype
      This table contains Optitype predictions
    render-table:
      columns:
        sample:
          link-to-url:
            SRA:
              url: "https://www.ncbi.nlm.nih.gov/sra/{value}"
  sample_sheet:
    dataset: sample_sheet
    desc: |
      ## Sample sheet
      This table contains samples and truth values for their HLA types belonging to samples evaluated in the paper.
      It shows excluded samples/individuals because of reasons, vg related issues related to low coverage and unavailability of fastq data.
    render-table:
      columns:
        Read_Length:
          plot:
            ticks:
              scale: linear
        Read_Count:
          plot:
            ticks:
              scale: linear
  runtimes:
    dataset: runtimes
    desc: |
      ## Runtimes of all tools including preprocessing steps.
    render-table:
      columns:
        max RSS mem in GB:
          plot:
            ticks:
              scale: linear
        runtime in minutes:
          plot:
            ticks:
              scale: linear
