#full path for the genomic HLA sequences and associated xml file. (here IMGT v3.32 is used.)
lineage_collection: /projects/koesterlab/orthanq/sars-cov-2-data/orthanq-evaluation/resources/ncbi_dataset/6_lineages.fasta

#arcasHLA database version
arcasHLA_version: "3.32.0"

#simulate reads or call for HLA types given a sample
simulation: True

#samples
samples: config/samples2.tsv

#viral lineages
viruses: config/lineages.tsv

#number of total reads in the sample
n_reads: 2000
n_nonhla_reads: 5000

##tool configurations
#art simulation
f_coverage: 50
