#full path for the genomic HLA sequences and associated xml file. (here IMGT v3.32 is used.)
allele_db: /home/uzuner/orthanq-evaluation/resources/IMGTHLA-3.32.0-alpha/hla_gen.fasta
allele_db_xml: /home/uzuner/orthanq-evaluation/resources/IMGTHLA-3.32.0-alpha/xml/hla.xml

#arcasHLA database version
arcasHLA_version: "3.32.0"

#simulate reads or call for HLA types given a sample
simulation: True

#samples
samples: config/samples_test.tsv

#alleles
hla: config/alleles.tsv

#number of total reads in the sample
n_reads: 2000
n_nonhla_reads: 5000

##tool configurations
#art simulation
f_coverage: 50
