#full path for the genomic HLA sequences and associated xml file. (here IMGT v3.36 is used.)
allele_db: /vol/compute/hamdiyes_project/orthanq-evaluation/resources/HLA-alleles/IMGTHLA-3.36.0-alpha/hla_gen.fasta
allele_db_xml: /vol/compute/hamdiyes_project/orthanq-evaluation/resources/HLA-alleles/IMGTHLA-3.36.0-alpha/xml/hla.xml

#arcasHLA database version
arcasHLA_version: "3.36.0"

#simulate reads or call for HLA types given a sample
simulation: False

#samples
samples: config/samples.tsv

#alleles
hla: config/alleles.tsv

#number of total reads in the sample
n_reads: 2000
n_nonhla_reads: 5000

##tool configurations
#art simulation
f_coverage: 50
