#full path for the genomic HLA sequences. (for now IMGT v3.33 is used.)
allele_db: /vol/compute/hamdiyes_project/orthanq-evaluation/resources/HLA-alleles/IMGT-3.33.0/IMGTHLA-3.33.0-alpha/hla_gen.fasta

#arcasHLA database version
arcasHLA_version: "3.24.0"

#simulate reads or call for HLA types given a sample
simulation: False

#samples
samples: config/samples2.tsv

#alleles
hla: config/alleles.tsv

#number of total reads in the sample
n_reads: 2000
n_nonhla_reads: 5000

##tool configurations
#art simulation
f_coverage: 50
